# **NUMPY**

In [1]:
import numpy as np
list_arr = [[1,2],[3,4]]
numpy_arr = np.array(list_arr) #to create numpy array from a list
print(numpy_arr)
print(numpy_arr.shape) #to get dimensions of numpy array
print(len(numpy_arr.shape)) #to get the number of dimensions of a numpy array

[[1 2]
 [3 4]]
(2, 2)
2


In [ ]:
print(list(range(8)))
print(np.arange(8)) #does the same as the list command in above line

[0, 1, 2, 3, 4, 5, 6, 7]
[0 1 2 3 4 5 6 7]


In [ ]:
print(np.zeros((2,4)))
print(np.ones((2,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
print(np.random.randint(8))
print(np.random.randint(8,size=(3,3,2)))


1
[[[7 1]
  [0 4]
  [0 3]]

 [[3 3]
  [4 4]
  [1 4]]

 [[6 3]
  [0 3]
  [3 6]]]


In [ ]:
print(np.random.random(3))

[0.51896633 0.4815579  0.62765311]


In [ ]:
numpy_arr_int8 = np.array(list_arr, dtype = np.int8)
print(numpy_arr_int8, numpy_arr_int8.dtype)
print(numpy_arr.dtype)

[[1 2]
 [3 4]] int8
int64


In [ ]:
numpy_arr_float16=np.array(numpy_arr, dtype = np.float16)
print(numpy_arr_float16, numpy_arr_float16.dtype)

[[1. 2.]
 [3. 4.]] float16


In [ ]:
numpy_arr_uint32=np.array(numpy_arr, dtype = np.uint32)
print(numpy_arr_uint32, numpy_arr_uint32.dtype)

[[1 2]
 [3 4]] uint32


In [ ]:
numpy_arr_bool=np.array([[0,1],[2,3]], dtype = np.bool)
print(numpy_arr_bool, numpy_arr_bool.dtype)

[[False  True]
 [ True  True]] bool


<ipython-input-10-c74d179bf88c>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  numpy_arr_bool=np.array([[0,1],[2,3]], dtype = np.bool)


In [ ]:
numpy_arr_complex256=np.array(numpy_arr, dtype = np.complex256)
print(numpy_arr_complex256, numpy_arr_complex256.dtype)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]] complex256


In [ ]:
print(numpy_arr.astype(np.complex128))
print(numpy_arr.astype(np.complex128).dtype)


[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
complex128


In [ ]:
print(np.random.rand(3,2))

[[0.6091455  0.33956839]
 [0.08505941 0.77534245]
 [0.15167911 0.4490783 ]]


In [ ]:
print(numpy_arr[0:,1])

[2 4]


In [ ]:
print(numpy_arr%2==1)

[[ True False]
 [ True False]]


In [ ]:
print(numpy_arr.T)

[[1 3]
 [2 4]]


In [ ]:
print(numpy_arr.sum(axis=1)) #axis=1 is row sum
print(numpy_arr.sum(axis=0)) #axis=0 is column sum

[3 7]
[4 6]


In [ ]:
b=[5,6]
print(np.array(b).shape)
print(numpy_arr+b)

(2,)
[[ 6  8]
 [ 8 10]]


In [ ]:
b=[[5],[6]]
print(np.array(b).shape)
print(numpy_arr+b)

(2, 1)
[[ 6  7]
 [ 9 10]]


In [ ]:
print(numpy_arr@b)

[[17]
 [39]]


In [ ]:
print(np.dot(numpy_arr,numpy_arr))

[[ 7 10]
 [15 22]]


In [2]:
np.zeros_like(list_arr)

array([[0, 0],
       [0, 0]])

In [3]:
np.ones_like(list_arr)

array([[1, 1],
       [1, 1]])

In [4]:
np.cumsum(list_arr)

array([ 1,  3,  6, 10])