<a href="https://colab.research.google.com/github/UKJaagadhep/Data-science-and-machine-learning/blob/main/Tensorflow%20Basics/Common_Tensorflow_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [23]:
a = tf.constant([
    [1,2.,3],
    [4.,3,2]
    ])

In [3]:
c = tf.constant([[14., 16, 9] , [16, 29, 80], [6, 89, 76]])

In [4]:
tf.expand_dims(a,0)

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [4., 3., 2.]]], dtype=float32)>

In [7]:
x = tf.expand_dims(a,1)
print(x)

tf.Tensor(
[[[1. 2. 3.]]

 [[4. 3. 2.]]], shape=(2, 1, 3), dtype=float32)


In [6]:
tf.expand_dims(a,2)

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [2.],
        [3.]],

       [[4.],
        [3.],
        [2.]]], dtype=float32)>

In [14]:
tf.squeeze(x, axis = 0)

InvalidArgumentError: {{function_node __wrapped__Squeeze_device_/job:localhost/replica:0/task:0/device:CPU:0}} Can not squeeze dim[0], expected a dimension of 1, got 2 [Op:Squeeze] name: 

In [15]:
tf.squeeze(x, axis = 1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 3., 2.]], dtype=float32)>

In [16]:
tf.squeeze(x, axis = 2)

InvalidArgumentError: {{function_node __wrapped__Squeeze_device_/job:localhost/replica:0/task:0/device:CPU:0}} Can not squeeze dim[2], expected a dimension of 1, got 3 [Op:Squeeze] name: 

In [17]:
tf.squeeze(x)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 3., 2.]], dtype=float32)>

In [18]:
tf.reshape(c, [1,9])

<tf.Tensor: shape=(1, 9), dtype=float32, numpy=array([[14., 16.,  9., 16., 29., 80.,  6., 89., 76.]], dtype=float32)>

In [19]:
c

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[14., 16.,  9.],
       [16., 29., 80.],
       [ 6., 89., 76.]], dtype=float32)>

In [21]:
tf.reshape(a,[3,-1])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [3., 2.]], dtype=float32)>

In [27]:
tf.concat([a,c], axis = 1)

InvalidArgumentError: {{function_node __wrapped__ConcatV2_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} ConcatOp : Dimension 0 in both shapes must be equal: shape[0] = [2,3] vs. shape[1] = [3,3] [Op:ConcatV2] name: concat

In [29]:
tf.concat([a,c], 0)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 1.,  2.,  3.],
       [ 4.,  3.,  2.],
       [14., 16.,  9.],
       [16., 29., 80.],
       [ 6., 89., 76.]], dtype=float32)>

In [30]:
tf.concat([a,a], 1)

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[1., 2., 3., 1., 2., 3.],
       [4., 3., 2., 4., 3., 2.]], dtype=float32)>

In [31]:
tf.stack([a,c], 0)

InvalidArgumentError: {{function_node __wrapped__Pack_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Shapes of all inputs must match: values[0].shape = [2,3] != values[1].shape = [3,3] [Op:Pack] name: stack

In [32]:
tf.stack([a,c], 1)

InvalidArgumentError: {{function_node __wrapped__Pack_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Shapes of all inputs must match: values[0].shape = [2,3] != values[1].shape = [3,3] [Op:Pack] name: stack

In [33]:
tf.stack([a,a], 0)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [4., 3., 2.]],

       [[1., 2., 3.],
        [4., 3., 2.]]], dtype=float32)>

In [34]:
tf.stack([a,a], 1)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [1., 2., 3.]],

       [[4., 3., 2.],
        [4., 3., 2.]]], dtype=float32)>

In [35]:
tf.stack([a,a,a,a,a], 0)

<tf.Tensor: shape=(5, 2, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [4., 3., 2.]],

       [[1., 2., 3.],
        [4., 3., 2.]],

       [[1., 2., 3.],
        [4., 3., 2.]],

       [[1., 2., 3.],
        [4., 3., 2.]],

       [[1., 2., 3.],
        [4., 3., 2.]]], dtype=float32)>

In [36]:
tf.stack([a,a,a,a,a], 1)

<tf.Tensor: shape=(2, 5, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]],

       [[4., 3., 2.],
        [4., 3., 2.],
        [4., 3., 2.],
        [4., 3., 2.],
        [4., 3., 2.]]], dtype=float32)>

In [37]:
tf.pad(c,paddings = [[2,2],[3,3]])

<tf.Tensor: shape=(7, 9), dtype=float32, numpy=
array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 14., 16.,  9.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 16., 29., 80.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  6., 89., 76.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)>

In [40]:
tf.pad(c,paddings = [[2,2],[3,3]], mode = 'CONSTANT', constant_values = [2,3])

InvalidArgumentError: {{function_node __wrapped__PadV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} constant_values must be a scalar. Found: [2] [Op:PadV2]

In [42]:
tf.pad(c,paddings = [[2,2],[3,3]], mode = 'CONSTANT', constant_values = 2)

<tf.Tensor: shape=(7, 9), dtype=float32, numpy=
array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2., 14., 16.,  9.,  2.,  2.,  2.],
       [ 2.,  2.,  2., 16., 29., 80.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  6., 89., 76.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.]], dtype=float32)>

In [56]:
tf.pad(c,paddings = [[2,2],[3,3]], mode = 'SYMMETRIC') #another mode = 'REFLECT'

<tf.Tensor: shape=(7, 9), dtype=float32, numpy=
array([[80., 29., 16., 16., 29., 80., 80., 29., 16.],
       [ 9., 16., 14., 14., 16.,  9.,  9., 16., 14.],
       [ 9., 16., 14., 14., 16.,  9.,  9., 16., 14.],
       [80., 29., 16., 16., 29., 80., 80., 29., 16.],
       [76., 89.,  6.,  6., 89., 76., 76., 89.,  6.],
       [76., 89.,  6.,  6., 89., 76., 76., 89.,  6.],
       [80., 29., 16., 16., 29., 80., 80., 29., 16.]], dtype=float32)>

In [57]:
tf.gather(c, indices = [0,2])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[14., 16.,  9.],
       [ 6., 89., 76.]], dtype=float32)>

In [59]:
tf.gather(c, indices = [2,0], axis = 1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 9., 14.],
       [80., 16.],
       [76.,  6.]], dtype=float32)>

In [65]:
tf.gather_nd(c,[1,0])

<tf.Tensor: shape=(), dtype=float32, numpy=16.0>

In [68]:
tf.gather_nd(c,[[1,1],[0,0]])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([29., 14.], dtype=float32)>

In [69]:
tf.gather_nd(c,[[1],[0]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[16., 29., 80.],
       [14., 16.,  9.]], dtype=float32)>

In [70]:
tf.gather_nd(c,[[1,1],[0]])

ValueError: Can't convert non-rectangular Python sequence to Tensor.