In [124]:
import numpy as np
import tensorflow as tf


In [125]:
tensor_0_d = tf.constant(1)
print(tensor_0_d)

tf.Tensor(1, shape=(), dtype=int32)


In [126]:
tensor_1_d = tf.constant([1,2,3])
print(tensor_1_d)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [127]:
tensor_2_d = tf.constant([[1,2],[2,3],[3,4],[4,5]])
print(tensor_2_d)

tf.Tensor(
[[1 2]
 [2 3]
 [3 4]
 [4 5]], shape=(4, 2), dtype=int32)


In [128]:
tensor_3_d = tf.constant([[[1,2],[2,3],[3,4],[4,5]],[[1,2],[2,3],[3,4],[4,5]],[[1,2],[2,3],[3,4],[4,5]]])
print(tensor_3_d)

tf.Tensor(
[[[1 2]
  [2 3]
  [3 4]
  [4 5]]

 [[1 2]
  [2 3]
  [3 4]
  [4 5]]

 [[1 2]
  [2 3]
  [3 4]
  [4 5]]], shape=(3, 4, 2), dtype=int32)


In [129]:
print(tensor_0_d.shape, tensor_0_d.ndim)
print(tensor_1_d.shape, tensor_1_d.ndim)
print(tensor_2_d.shape, tensor_2_d.ndim)
print(tensor_3_d.shape, tensor_3_d.ndim)

() 0
(3,) 1
(4, 2) 2
(3, 4, 2) 3


In [130]:
tf.constant(4, shape = [2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 4, 4],
       [4, 4, 4]], dtype=int32)>

In [131]:
tf.constant([[4,5],[5,6]], dtype = tf.float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 5.],
       [5., 6.]], dtype=float32)>

In [132]:
tf.constant(4, shape = [2,3], dtype = tf.float32)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4., 4., 4.],
       [4., 4., 4.]], dtype=float32)>

In [134]:
tf.constant(4.6,shape = [2,4], dtype = tf.int32)

TypeError: Cannot convert 4.6 to EagerTensor of dtype int32

In [135]:
tf.cast(tf.constant(4.6,shape = [2,4]), tf.int32)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 4, 4, 4],
       [4, 4, 4, 4]], dtype=int32)>

In [136]:
tf.cast(tf.constant([[4,5],[5,0],[0.0,1]]),tf.bool)

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True, False],
       [False,  True]])>

In [137]:
tf.constant(['hello world'])

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'hello world'], dtype=object)>

In [138]:
tf.constant([['hello world', 'hi'],['hello world', 'hi'],['hello world', 'hi']])

<tf.Tensor: shape=(3, 2), dtype=string, numpy=
array([[b'hello world', b'hi'],
       [b'hello world', b'hi'],
       [b'hello world', b'hi']], dtype=object)>

In [139]:
np_arr = np.array([[1,2,3],[4,5,6]])
numpy_to_tensor = tf.constant(np_arr)
print(numpy_to_tensor)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


In [140]:
numpy_to_tensor_2 = tf.convert_to_tensor(np_arr)
print(numpy_to_tensor_2)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


In [141]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [142]:
tf.eye(4, num_columns = 2)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [143]:
tf.eye(4, num_columns = 6)

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]], dtype=float32)>

In [144]:
tf.eye(4, batch_shape = [2,3])

<tf.Tensor: shape=(2, 3, 4, 4), dtype=float32, numpy=
array([[[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]]],


       [[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]]]], dtype=float32)>

In [145]:
identity_ = tf.eye(4, dtype = tf.int32)
print(identity_)

tf.Tensor(
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]], shape=(4, 4), dtype=int32)


In [146]:
tf.eye(4, dtype = tf.bool)

<tf.Tensor: shape=(4, 4), dtype=bool, numpy=
array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])>

In [147]:
4 * identity_

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[4, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 4]], dtype=int32)>

In [148]:
3 * tensor_2_d

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  6],
       [ 6,  9],
       [ 9, 12],
       [12, 15]], dtype=int32)>

In [149]:
tf.fill([2,5],9)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]], dtype=int32)>

In [150]:
tf.fill([2,5],[9,3])

InvalidArgumentError: {{function_node __wrapped__Fill_device_/job:localhost/replica:0/task:0/device:CPU:0}} value must represent a scalar, got shape [2] [Op:Fill]

In [151]:
tf.ones([2,8])

<tf.Tensor: shape=(2, 8), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [152]:
tf.ones([2,8], dtype = tf.bool)

<tf.Tensor: shape=(2, 8), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])>

In [153]:
tf.ones_like(tensor_2_d)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)>

In [154]:
tf.ones_like(tensor_2_d, dtype = tf.float32)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [155]:
tf.zeros([2,8])

<tf.Tensor: shape=(2, 8), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [156]:
tf.zeros([2,8], dtype = tf.bool)

<tf.Tensor: shape=(2, 8), dtype=bool, numpy=
array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])>

In [157]:
tf.zeros_like(tensor_2_d)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)>

In [158]:
zero_ = tf.zeros_like(tensor_2_d, dtype = tf.float32)

In [159]:
tf.rank(tensor_2_d)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [160]:
tf.rank(tensor_1_d)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [161]:
tf.rank(tensor_3_d)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [162]:
tf.rank(zero_)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [163]:
tf.size(tensor_1_d) #returns no. of elements in tensor

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [164]:
tf.size(tensor_2_d) #returns no. of elements in tensor

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [165]:
tf.random.normal([2,6], mean = 30, stddev = 5, dtype = tf.float16, seed = 10)

<tf.Tensor: shape=(2, 6), dtype=float16, numpy=
array([[27.72, 33.75, 28.6 , 36.06, 31.89, 37.12],
       [27.1 , 23.36, 33.9 , 36.44, 31.16, 27.81]], dtype=float16)>

In [166]:
tf.random.normal([2,6])

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 0.59687006,  0.02748929,  1.1587435 , -0.22770977, -0.6168055 ,
        -0.13793416],
       [ 1.594074  ,  0.35814193, -0.10478067, -0.3571028 ,  0.38818938,
         1.7014629 ]], dtype=float32)>

In [188]:
tf.random.uniform([2,3], minval = 30, maxval = 600, dtype = tf.int32, seed = 10)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[559,  52, 270],
       [264, 446, 120]], dtype=int32)>

In [189]:
tf.random.uniform([2,3], minval = 30, maxval = 600, dtype = tf.int32, seed = 10)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[182, 188, 201],
       [307, 153, 409]], dtype=int32)>

In [190]:
tf.random.uniform([2,3]) #minval = 0, maxval = 1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.55478156, 0.42658198, 0.14140713],
       [0.703694  , 0.3726666 , 0.6976985 ]], dtype=float32)>

In [185]:
tf.random.set_seed(10)
tf.random.uniform([2,3], minval = 30, maxval = 600, dtype = tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[420, 203, 476],
       [190, 246, 460]], dtype=int32)>

In [191]:
tf.random.set_seed(10) #sets the seed glabally for all functions
tf.random.uniform([2,3], minval = 30, maxval = 600, dtype = tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[420, 203, 476],
       [190, 246, 460]], dtype=int32)>