<a href="https://colab.research.google.com/github/UKJaagadhep/Data-science-and-machine-learning/blob/main/Tensorflow%20Basics/Linear_Algebra_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([
    [1,2,3],
    [4.,3,2]
    ])

In [3]:
b = a.T

AttributeError: EagerTensor object has no attribute 'T'. 
        If you are looking for numpy-related methods, please run the following:
        tf.experimental.numpy.experimental_enable_numpy_behavior()
      

In [5]:
b = tf.transpose(a)
print(b)

tf.Tensor(
[[1. 4.]
 [2. 3.]
 [3. 2.]], shape=(3, 2), dtype=float32)


In [6]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 16.],
       [16., 29.]], dtype=float32)>

In [7]:
a@b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 16.],
       [16., 29.]], dtype=float32)>

In [8]:
tf.matmul(a,a, transpose_b = True)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 16.],
       [16., 29.]], dtype=float32)>

In [9]:
tf.linalg.adjoint(a)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 3.],
       [3., 2.]], dtype=float32)>

In [10]:
c = tf.constant([[14., 16, 9] , [16, 29, 80], [6, 89, 76]])
print(c)

tf.Tensor(
[[14. 16.  9.]
 [16. 29. 80.]
 [ 6. 89. 76.]], shape=(3, 3), dtype=float32)


In [11]:
tf.linalg.band_part(c,0,0)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[14.,  0.,  0.],
       [ 0., 29.,  0.],
       [ 0.,  0., 76.]], dtype=float32)>

In [12]:
tf.linalg.band_part(c,0,-1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[14., 16.,  9.],
       [ 0., 29., 80.],
       [ 0.,  0., 76.]], dtype=float32)>

In [13]:
tf.linalg.band_part(c,-1,0)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[14.,  0.,  0.],
       [16., 29.,  0.],
       [ 6., 89., 76.]], dtype=float32)>

In [14]:
tf.linalg.cross(a,a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [15]:
tf.linalg.det(c)

<tf.Tensor: shape=(), dtype=float32, numpy=-69349.984>

In [16]:
tf.linalg.det(a)

InvalidArgumentError: {{function_node __wrapped__MatrixDeterminant_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input matrix must be square. [Op:MatrixDeterminant] name: 

In [17]:
d = tf.linalg.inv(c)
print(d)
print(c@d)
print(d@c)

tf.Tensor(
[[ 0.07088681  0.00598414 -0.01469358]
 [ 0.01061283 -0.01456381  0.01407354]
 [-0.01802451  0.01658255 -0.00216294]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 1.0000000e+00  7.8231096e-08  1.1641532e-09]
 [-2.9802322e-08  1.0000001e+00  3.7252903e-09]
 [ 7.4505806e-09  1.6391277e-07  1.0000000e+00]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1.0000001e+00 1.6950071e-07 3.0547380e-07]
 [2.2351742e-08 1.0000000e+00 1.0430813e-07]
 [1.0710210e-08 1.9790605e-08 1.0000000e+00]], shape=(3, 3), dtype=float32)


In [18]:
tf.linalg.svd(c) #outputs 3 tensors

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([142.31682 ,  36.47546 ,  13.359478], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.1308502 , -0.09679975,  0.9866651 ],
        [ 0.5708473 ,  0.8210421 ,  0.00484585],
        [ 0.8105628 , -0.562601  , -0.16269141]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.11122254,  0.23045276,  0.96670616],
        [ 0.6379308 , -0.762432  ,  0.10836   ],
        [ 0.7620197 ,  0.6046396 , -0.23181254]], dtype=float32)>)

In [19]:
tf.linalg.trace(c)

<tf.Tensor: shape=(), dtype=float32, numpy=119.0>

In [20]:
tf.linalg.trace(a)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [21]:
tf.linalg.svd(a)

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([6.2586412, 1.9568859], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.5364542, -0.8439294],
        [-0.8439294,  0.5364542]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.6250831 ,  0.66528517],
        [-0.5759551 , -0.04011298],
        [-0.52682704, -0.7455109 ]], dtype=float32)>)

In [28]:
tf.einsum("ij->ji",a) #transpose

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 3.],
       [3., 2.]], dtype=float32)>

In [29]:
tf.einsum("ij,jk->ik",a,c) #matrix multiplication

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 64., 341., 397.],
       [116., 329., 428.]], dtype=float32)>

In [30]:
tf.einsum("ij->",a) #sum of elements in matrix

<tf.Tensor: shape=(), dtype=float32, numpy=15.0>

In [34]:
tf.einsum("ij->j",a) #sum of elements each column in matrix

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([5., 5., 5.], dtype=float32)>

In [35]:
tf.einsum("ij->i",a) #sum of elements in each row in matrix

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([6., 9.], dtype=float32)>