<a href="https://colab.research.google.com/github/UKJaagadhep/Data-science-and-machine-learning/blob/main/Tensorflow%20Basics/Maths_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.range(2,8)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7], dtype=int32)>

In [3]:
tf.range(4.,8.)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([4., 5., 6., 7.], dtype=float32)>

In [4]:
tf.range(4.5,13.9,2)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 4.5,  6.5,  8.5, 10.5, 12.5], dtype=float32)>

In [5]:
tf.abs([-1,2,3,-5.5])

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1. , 2. , 3. , 5.5], dtype=float32)>

In [6]:
tf.abs(tf.constant([[-1,-2,-3],[4,-5,6],[-7,8,-9]]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [7]:
tf.sqrt([9,16])

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [8]:
tf.sqrt([9.,16.,12.])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3.       , 4.       , 3.4641016], dtype=float32)>

In [9]:
tf.add([[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  7],
       [ 7,  9],
       [ 9, 11]], dtype=int32)>

In [10]:
tf.add([[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]],[[7,8],[8,9],[9,10]])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  7],
       [ 7,  9],
       [ 9, 11]], dtype=int32)>

In [11]:
tf.add([[1,2],[2,3],[3,4]],[7])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  9],
       [ 9, 10],
       [10, 11]], dtype=int32)>

In [12]:
tf.multiply([[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4, 10],
       [10, 18],
       [18, 28]], dtype=int32)>

In [13]:
x = tf.constant([[1,2],[2,3],[3,4]])
y = tf.constant([[4,5],[5,6],[6,7]])
x*y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4, 10],
       [10, 18],
       [18, 28]], dtype=int32)>

In [14]:
tf.subtract([[1,2],[2,3],[3,4]],[4])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[-3, -2],
       [-2, -1],
       [-1,  0]], dtype=int32)>

In [15]:
x-y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[-3, -3],
       [-3, -3],
       [-3, -3]], dtype=int32)>

In [16]:
tf.divide([[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]])

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.25      , 0.4       ],
       [0.4       , 0.5       ],
       [0.5       , 0.57142857]])>

In [17]:
x/y

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.25      , 0.4       ],
       [0.4       , 0.5       ],
       [0.5       , 0.57142857]])>

In [18]:
tf.divide([[1,2],[2,3],[3,4]],[[4,0],[5,0],[6,0]])

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.25,  inf],
       [0.4 ,  inf],
       [0.5 ,  inf]])>

In [19]:
tf.math.divide_no_nan([[1,2],[2,3],[3,4]],[[4,0],[5,0],[6,0]])

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.25, 0.  ],
       [0.4 , 0.  ],
       [0.5 , 0.  ]])>

In [20]:
tf.maximum([[1,2],[2,3],[3,4]],[[4,0],[5,0],[6,0]])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 2],
       [5, 3],
       [6, 4]], dtype=int32)>

In [21]:
tf.minimum([[1,2],[2,3],[3,4]],[[4,0],[5,0],[6,0]])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [2, 0],
       [3, 0]], dtype=int32)>

In [22]:
tf.argmax([[1,2],[2,3],[3,4]], axis = 1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 1])>

In [23]:
tf.argmin([[1,2],[2,3],[3,4]], axis = 1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 0, 0])>

In [27]:
tf.equal([[1.,2],[2,3],[3,4]],[[4,2.],[5,0],[6,0]])

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False,  True],
       [False, False],
       [False, False]])>

In [28]:
tf.pow([[1,2],[2,3],[3,4]],[[4,0],[5,0],[6,0]])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  1,   1],
       [ 32,   1],
       [729,   1]], dtype=int32)>

In [29]:
tf.reduce_sum([[1,2],[2,3],[3,4]])

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [30]:
tf.reduce_sum([[1,2],[2,3],[3,4]], axis = 0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 9], dtype=int32)>

In [31]:
tf.reduce_sum([[1,2],[2,3],[3,4]], axis = 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7], dtype=int32)>

In [32]:
tf.reduce_max([[1,2],[2,3],[3,4]])

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [33]:
tf.reduce_max([[1,2],[2,3],[3,4]], axis = 0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [34]:
tf.reduce_max([[1,2],[2,3],[3,4]], axis = 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [35]:
tf.reduce_min([[1,2],[2,3],[3,4]])

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [36]:
tf.reduce_min([[1,2],[2,3],[3,4]], axis = 0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [38]:
tf.reduce_min([[1,2],[2,3],[3,4]], axis = 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [41]:
tf.reduce_mean([[1,2],[2,3],[3,4]])

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [42]:
tf.reduce_mean([[1,2],[2,3],[3,4.]])

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [43]:
tf.reduce_mean([[1,2],[2,3],[3,4]], axis = 0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [44]:
tf.reduce_mean([[1,2],[2,3],[3,4.]], axis = 0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [45]:
tf.reduce_mean([[1,2],[2,3],[3,4]], axis = 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [46]:
tf.reduce_mean([[1,2.],[2,3],[3,4]], axis = 1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.5, 2.5, 3.5], dtype=float32)>

In [49]:
tf.math.reduce_std([[1,2.],[2,3],[3,4]])

<tf.Tensor: shape=(), dtype=float32, numpy=0.95742714>

In [53]:
tf.math.reduce_std([[1,2],[2,3],[3,4.]], axis = 0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.8164966, 0.8164966], dtype=float32)>

In [54]:
tf.math.reduce_std([[1,2],[2,3],[3,4.]], axis = 1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.5, 0.5, 0.5], dtype=float32)>

In [58]:
tf.sigmoid([[1,2],[2,3],[3,4.]])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7310586 , 0.8807971 ],
       [0.8807971 , 0.95257413],
       [0.95257413, 0.98201376]], dtype=float32)>

In [61]:
tf.math.top_k([[1,2],[2,3],[3,4.]])

TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[2.],
       [3.],
       [4.]], dtype=float32)>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [1],
       [1]], dtype=int32)>)

In [62]:
tf.math.top_k([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]],[[7,8],[8,9],[9,10]]])

TopKV2(values=<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10]]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]], dtype=int32)>)

In [63]:
tf.math.top_k([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]],[[7,8],[8,9],[9,10]]], k = 2)

TopKV2(values=<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[ 2,  1],
        [ 3,  2],
        [ 4,  3]],

       [[ 5,  4],
        [ 6,  5],
        [ 7,  6]],

       [[ 8,  7],
        [ 9,  8],
        [10,  9]]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[1, 0],
        [1, 0],
        [1, 0]],

       [[1, 0],
        [1, 0],
        [1, 0]],

       [[1, 0],
        [1, 0],
        [1, 0]]], dtype=int32)>)

In [64]:
tf.math.top_k([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]],[[7,8],[8,9],[9,10]]], k = 2, sorted = False)

TopKV2(values=<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[ 2,  1],
        [ 3,  2],
        [ 4,  3]],

       [[ 5,  4],
        [ 6,  5],
        [ 7,  6]],

       [[ 8,  7],
        [ 9,  8],
        [10,  9]]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[1, 0],
        [1, 0],
        [1, 0]],

       [[1, 0],
        [1, 0],
        [1, 0]],

       [[1, 0],
        [1, 0],
        [1, 0]]], dtype=int32)>)