<a href="https://colab.research.google.com/github/UKJaagadhep/Data-science-and-machine-learning/blob/main/Tensorflow%20Basics/Ragged%2C_Sparse%2C_String_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

**RAGGED TENSORS**

In [2]:
a = tf.ragged.constant([[1],[4,2,5],[5,9]])

In [3]:
print(a)
print(a.shape)

<tf.RaggedTensor [[1], [4, 2, 5], [5, 9]]>
(3, None)


In [4]:
tf.ragged.boolean_mask(a, mask = tf.ragged.constant([[True],[True,False,False],[True,True]]))

<tf.RaggedTensor [[1], [4], [5, 9]]>

In [5]:
tf.ragged.boolean_mask(a, mask = tf.ragged.constant([True, True, False]))

<tf.RaggedTensor [[1], [4, 2, 5]]>

In [6]:
tf.RaggedTensor.from_row_lengths(values = [3,1,4,1,5,9,2,6], row_lengths = [4,0,3,0,1])

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [], [6]]>

In [7]:
tf.RaggedTensor.from_row_limits(values = [3,1,4,1,5,9,2,6], row_limits = [4,4,7,7,8])

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [], [6]]>

In [8]:
tf.RaggedTensor.from_row_splits(values = [3,1,4,1,5,9,2,6], row_splits = [0,4,4,7,7,8])

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [], [6]]>

In [9]:
b = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(tf.RaggedTensor.from_tensor(b))
print(tf.RaggedTensor.from_tensor(b, lengths = [1,3,0]))

<tf.RaggedTensor [[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]>
<tf.RaggedTensor [[1], [4, 5, 6], []]>


**SPARSE TENSORS**

In [13]:
sparse = tf.sparse.SparseTensor(indices = [[0,1],[1,1],[1,3],[2,2],[2,4]], values = [5,6,7,8,9], dense_shape = [5,6])
print(sparse)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 1]
 [1 3]
 [2 2]
 [2 4]], shape=(5, 2), dtype=int64), values=tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [14]:
tf.sparse.to_dense(sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[0, 5, 0, 0, 0, 0],
       [0, 6, 0, 7, 0, 0],
       [0, 0, 8, 0, 9, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>

**STRING TENSORS**

In [15]:
string_ = tf.constant([['ji','hello'],['ok','go'],['suf','tuk']])

In [18]:
tf.strings.join(string_)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'jioksuf', b'hellogotuk'], dtype=object)>

In [19]:
tf.strings.join(string_, separator = '+')

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'ji+ok+suf', b'hello+go+tuk'], dtype=object)>

In [20]:
tf.strings.length(string_)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 5],
       [2, 2],
       [3, 3]], dtype=int32)>

In [21]:
s = tf.strings.upper(string_)
print(s)

tf.Tensor(
[[b'JI' b'HELLO']
 [b'OK' b'GO']
 [b'SUF' b'TUK']], shape=(3, 2), dtype=string)


In [22]:
tf.strings.lower(s)

<tf.Tensor: shape=(3, 2), dtype=string, numpy=
array([[b'ji', b'hello'],
       [b'ok', b'go'],
       [b'suf', b'tuk']], dtype=object)>