<a href="https://colab.research.google.com/github/UKJaagadhep/Data-science-and-machine-learning/blob/main/Tensorflow%20Basics/Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [3]:
a = tf.Variable([[1,2,3],[4,5,6]])
print(a)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>


In [9]:
a.assign_add([[8,1,2],[6,6,6]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 9,  3,  5],
       [10, 11, 12]], dtype=int32)>

In [10]:
a.assign_sub([[8,1,2],[6,6,6]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [11]:
a.assign([[8,1,2],[6,6,6]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[8, 1, 2],
       [6, 6, 6]], dtype=int32)>

In [12]:
print(a)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[8, 1, 2],
       [6, 6, 6]], dtype=int32)>


In [13]:
tf.device('GPU:0')